### ISSUE TITLE
Compile failure after upgrade NumShape to v0.6

### ISSUE THREAD

**Issue by Oceania2018** [Proxem/NumNet#2]

**Comment by thp-proxem** [comment]
Hi, I pushed a fix, it should work now. However I think there's a bug in your np.random.normal function which returns a flat vector when given two int as shape...

**Comment by dotChris90** [comment]
@thp-proxem hey thanks for let us know. ;) Indeed you right - was a side effect in our internal Storage strategy. we generated a new 1D array and overwrote the old internal 1D array in our NDArray - unfortunately our shape was also overwritten. -.- 

So thanks - is now fixed in master branch but not released.
